export const SITE_CONFIG = {
  name: "Forgeora",
  title: "Forgeora - Innovative Software Solutions",
  description: "Forgeora is a leading software company specializing in AI, physics simulations, and cutting-edge technology solutions. Discover our services and expertise.",
  keywords: "software company, AI, physics simulations, technology solutions, Forgeora",
  authors: [{ name: "Forgeora Team" }],
  creator: "Forgeora Team",
  publisher: "Forgeora",
  robots: "index, follow",
  canonical: "https://forgeora.com",
  openGraph: {
    title: "Forgeora - Innovative Software Solutions",
    description: "Leading software company in AI and physics simulations",
    type: "website",
    url: "https://forgeora.com",
    siteName: "Forgeora",
    images: [
      {
        url: "/logo-header.png",
        width: 1200,
        height: 630,
        alt: "Forgeora Logo",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Forgeora - Innovative Software Solutions",
    description: "Leading software company in AI and physics simulations",
    images: ["/logo-header.png"],
    site: "@forgeora",
    creator: "@forgeora",
  },
  mission: "At Forgeora, we are committed to pushing the boundaries of technology to solve complex problems and create innovative solutions that make a difference in the world.",
  tagline: "Forgeora specializes in cutting-edge AI, physics simulations, and technology solutions that drive innovation and transform businesses.",
  contactIntro: "Ready to transform your ideas into reality? Let's discuss how Forgeora can help bring your vision to life.",
  reviewsIntro: "Don't just take our word for it. Here's what our clients have to say about working with Forgeora.",
  aboutIntro: "Learn more about our mission, vision, and the team behind Forgeora.",
  copyright: "© 2025 Forgeora. All rights reserved.",
  socialLinks:{
    linkedin: "https://www.linkedin.com/company/forgeora",
    twitter: "https://twitter.com/forgeora",
    github: "https://github.com/forgeora",
    instagram : "https://www.instagram.com/forgeora",
  }
};
